services:
  backend:
    build:
      context: ./backend
      args:
        DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
