services:
  backend:
    build:
      context: ./backend
      args:
        DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
        ADMINISTRATOR_ROLE_ID: ${ADMINISTRATOR_ROLE_ID}
        TEACHER_ROLE_ID: ${TEACHER_ROLE_ID}
        STUDENT_ROLE_ID: ${STUDENT_ROLE_ID}
        GUILD_ID: ${GUILD_ID}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_SERVICE_ROLE_KEY: ${VITE_SUPABASE_SERVICE_ROLE_KEY}
        SUPABASE_DIRECT_URL: ${SUPABASE_DIRECT_URL}
        REDIS_URL: ${REDIS_URL}
        FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - config_data:/backend/data
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_SERVICE_ROLE_KEY: ${VITE_SUPABASE_SERVICE_ROLE_KEY}
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  redis:
    image: redis:7.4.0-alpine3.20
    restart: always
    ports:
      - "6379:6379"

volumes:
  redis_data:
  config_data:
