services:
  backend:
    build:
      context: ./backend
      args:
        DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
        ADMINISTRATOR_ROLE_ID: ${ADMINISTRATOR_ROLE_ID}
        TEACHER_ROLE_ID: ${TEACHER_ROLE_ID}
        STUDENT_ROLE_ID: ${STUDENT_ROLE_ID}
        GUILD_ID: ${GUILD_ID}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_SERVICE_ROLE_KEY: ${VITE_SUPABASE_SERVICE_ROLE_KEY}
        SUPABASE_DIRECT_URL: ${SUPABASE_DIRECT_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_SERVICE_ROLE_KEY: ${VITE_SUPABASE_SERVICE_ROLE_KEY}
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
